### PR TITLE
[IMPAC-741] Lmi widgets improvement

### PR DESCRIPTION
**Pull request by iseessel**
@MarcoBgn

### CODE REVIEW

**Comment by MarcoBgn** [comment]
@iseessel after cloning and testing in local this seems to have an unintended effect:
- As per your PR:
screen shot 2018-02-27 at 10 58 16


- As it was originally:
screen shot 2018-02-27 at 11 00 12

This way some column might be obscured, especially if more I-C sets are introduced. 

The legend spacing looks good.

**Comment by MarcoBgn** [comment]
I will also ask for a new branch on Maestrano's, so PR's can be reviewed and managed there.

**Review by xaun — APPROVED** [review]

**Comment by xaun** [comment]
Approving the changes as Marco asked for a review, as you would know @iseessel, if this is going to be merged into maestrano releases, it will need to be changed for your refactor on the HighchartsFactory. If not then the addition are ok for me.

**Comment by iseessel** [comment]
@MarcoBgn The left axis represents average visits per customer which is: "The total transaction count at the store divided by the number of customers in the same time period."

As far as I'm concerned, this is not a $ , but are number of transactions per person.

**Comment by MarcoBgn** [comment]
@iseessel yes, definitely. My bad, I rushed through and thought about the average spend. I have deleted the comment. Just waiting for the branch to be created 👍

**Comment by iseessel** [comment]
@MarcoBgn Sounds great!

@xaun And believe me that has occurred to me ;).

**Pull request merged**
